### ISSUE TITLE
About training image size for DAVIS

### ISSUE THREAD

**Issue by chenz97** [HuaijiaLin/AGSS-VOS#3]
Hi, thank you for your great work and code!

When I was training with your script, I found that the image size for DAVIS is not 320*640 as specified in the paper, but 448*832. Is it a mistake, or do you get your results in the paper using 448*832 for DAVIS?

Thank you very much!

**Comment by HuaijiaLin** [comment]
@chenz97 
Thanks for your attention to this work. For the training details, please take this code as the standard.

**Comment by chenz97** [comment]
Hi @HuaijiaLin . Thanks for your reply! I'm closing the issue.
